### ISSUE TITLE
React Native 0.63.x Error: RNHTMLtoPDF error: Could not create folder structure.

### ISSUE THREAD

**Issue by fxbayuanggara** [christopherdro/react-native-html-to-pdf#189]
There is a problem when using React Native 0.63.x: Error: RNHTMLtoPDF error: Could not create folder structure.

I have to downgrade my React Native to 0.62.x to get it worked,

And also downgrade the build.gradle (android) to 3.5.2
buildscript {
    ..
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by MahmonirB** [comment]
I use this package in RN 0.62.2 and I have this error:  `Could not create folder structure`.
what should I do?

**Comment by fxbayuanggara** [comment]
@MahmonirB try to downgrade your build gradle tools too to 3.5.2.

**Comment by MahmonirB** [comment]
My build gradle tools is current 3.5.2:
classpath("com.android.tools.build:gradle:3.5.2")

**Comment by brunoconterato** [comment]
Problem solved in Android when I asked the user permission for WRITE_EXTERNAL_STORAGE.

**Comment by zhuweideng** [comment]
i add code to request storage permission,then i can create folder structure
`async requestReadPermission() {
        try {
            //返回string类型
            const granted = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                {
                    //第一次请求拒绝后提示用户你为什么要这个权限
                    'title': '申请读写权限',
                    'message': '想要申请读写权限，禁止申请权限将无法继续操作',
                    buttonNeutral: '等会再询问',
                    buttonNegative: '禁止',
                    buttonPositive: '继续',
                }
            )
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                Toast.message('你已获取了读写权限');
                this.createPDF();
            } else {
                Toast.message('获取读写权限失败');
            }
        } catch (err) {
            Toast.message(err.toString());
        }
    }`

**Comment by dharmikvyas** [comment]
I have same problem.
Everything works fine with ANDROID API LEVEL 28 AND 30. But Crashes in API LEVEL 29.
I have changed gradle to `3.5.2` and RN to `0.62.2`.
thn my full app crash, not starting. So I have to stick to newer version.
But still crashes on real device and on simulator it says
Could not create folder structure
My Android Logcat Output Says,
```
FATAL EXCEPTION: main
    Process: com.pdfconverter, PID: 13456
    java.lang.IllegalArgumentException: fd cannot be null
        at dp.onWrite(PG:27)
        at android.print.PdfConverter$1.onPageFinished(PdfConverter.java:71)
        at O7.b(PG:2)
        at Do.handleMessage(PG:65)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:221)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by dharmikvyas** [comment]
I got following error if I change `RN:0.62.2` and `Gradle:3.5.2`
```
error: Error: Unable to resolve module `./Libraries/Components/Pressable/Pressable` from `node_modules/react-native/index.js`:

None of these files exist:
  * node_modules/react-native/Libraries/Components/Pressable/Pressable(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native/Libraries/Components/Pressable/Pressable/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Project/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
```

**Comment by dharmikvyas** [comment]
@fxbayuanggara  how did you solved this? Is there any other changes to make?

**Comment by DnEgorWeb** [comment]
For some reason, for react-native `0.63` it works only with programatically asking permission. For versions below `0.63` it was fine just with the permission of WRITE_EXTERNAL_STORAGE in AndroidManifest

**Comment by talut** [comment]
If you encounter with this issue above API 29 you should add this `android:requestLegacyExternalStorage="true"` to <application> in AndroidManifest.xml

**Comment by dharmikvyas** [comment]
> If you encounter with this issue above API 29 you should add this `android:requestLegacyExternalStorage="true"` to `<application>` in AndroidManifest.xml

It works. Thank you so much..

**Comment by borgen12** [comment]
@talut Am I reading the docs correctly in that this is a temporary fix and will be deprecated by Android 11? https://developer.android.com/about/versions/11/privacy/storage#maintain-compatibility-android-10

**Comment by dillonkuester** [comment]
> @talut Am I reading the docs correctly that this is a temporary fix and will be deprecated by Android 11? https://developer.android.com/about/versions/11/privacy/storage#maintain-compatibility-android-10

It appears so.

> > If you encounter with this issue above API 29 you should add this `android:requestLegacyExternalStorage="true"` to `<application>` in AndroidManifest.xml
> 
> It works. Thank you so much..

Can you confirm this works? My pdf is blank.

**Comment by borgen12** [comment]
@dillonkuester this worked for me in that my app is no longer crashing but I am also getting a blank pdf.

**Comment by borgen12** [comment]
@dillonkuester This fixed the issue of my app crashing but some of my pdf wasn't rendering which was partially fixed by this thread: https://github.com/christopherdro/react-native-html-to-pdf/issues/106

**Comment by talut** [comment]
@dillonkuester @borgen12  Yes, it'll deprecated. Also I solve blank PDF issue with fork of this package. You can find here https://github.com/jdaoliveira/react-native-html-to-pdf

**Comment by schmidtmc** [comment]
> @dillonkuester @borgen12 Yes, it'll deprecated. Also I solve blank PDF issue with fork of this package. You can find here https://github.com/jdaoliveira/react-native-html-to-pdf

What was the cause of that blank PDF issue?

**Comment by SahanDll** [comment]
> @dillonkuester @borgen12 Yes, it'll deprecated. Also I solve blank PDF issue with fork of this package. You can find here https://github.com/jdaoliveira/react-native-html-to-pdf

What is the fix?

**Comment by talut** [comment]
I just tried a fork of this package. Which I found in older issues: https://github.com/christopherdro/react-native-html-to-pdf/issues/158#issuecomment-673093264

**Comment by SahanDll** [comment]
> I just tried a fork of this package and its worked and I didn't ask question for why 😄 . Which I found in older issues: [#158 (comment)](https://github.com/christopherdro/react-native-html-to-pdf/issues/158#issuecomment-673093264)

Found the solution. It happens when sdk 29 support added. From your fork (only needs PdfConverter.java file) i have created a patch in my project. Now it's working. (Y)

**Comment by firdaussoberi** [comment]
> @dillonkuester This fixed the issue of my app crashing but some of my pdf wasn't rendering which was partially fixed by this thread: #106

I also have this problem when using api 29 despite RN0.60.4. Sometimes half of the pdf is blank while some pdf is just total blank. Using version 0.6.0 of this library (because using 0.8.0 would just make the app crash) 

Had to revert back to api 28 to make it work. It's not urgent at the moment but until Nov 2nd, we all have to switch to api 29. I wonder if there is a consistent fix.

**Comment by Bilal-Abdeen** [comment]
It seems that the recent versions of Android do not allow access to the "Documents" folder. Moreover, access to other folders needs permission. 

I have NOT tried the following solution on iOS. Please, let us know if it works on iOS. It might be necessary to check for the OS before assigning a value to the "options.directory" property.

1. The following change needs to be applied to the options object. 
```javascript 
    let options = {
      html: '<h1>PDF TEST</h1>',
      fileName: 'test',
      directory: 'Download', // replace "Documents" with "Download" - I am not sure if this works on iOS 
    };
```

2. Moreover, you need to add a function to request permission. This is already mentioned on the readme file. However, it might not be obvious. An example code follows. 
```javascript 
import { Platform, PermissionsAndroid, } from "react-native";
import RNHTMLtoPDF from 'react-native-html-to-pdf';

const fRequestAndroidPermission = async () => {
	// Refer to https://reactnative.dev/docs/permissionsandroid for further details on permsissions 
	try {
		const granted = await PermissionsAndroid.request(
			PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
			{
				title: "App1 Permission Request",
				message: "App1 needs access to your storage so you can save files to your device.",
				buttonNeutral: "Ask Me Later",
				buttonNegative: "Cancel",
				buttonPositive: "OK"
			}
		);
		
		if (granted === PermissionsAndroid.RESULTS.GRANTED) {
			console.log("permission is granted");
			return true; 
		} else {
			console.log("permission denied");
			return false; 
		}
	} catch (err) {
		console.error("fRequestAndroidPermission error:", err);
		return false; 
	}
};

const createPDF = async () => {
	let options = {
	  html: '<h1>PDF TEST</h1>',
	  fileName: 'test',
	  directory: 'Documents', // replace 'Documents' with 'Dowloads' - I am not sure if it works on iOS! 
	};

	if (Platform.OS === "android") {
		const permissionGranted = await fRequestAndroidPermission(); 
		if (!permissionGranted) {
			console.log("access was refused")
			return; 
		}
	}

	let file = await RNHTMLtoPDF.convert(options);
	console.log(file.filePath);
};
createPDF(); 
```

**Comment by StephenTANM** [comment]
> It seems that the recent versions of Android do not allow access to the "Documents" folder. Moreover, access to other folders needs permission.
> 
> I have NOT tried the following solution on iOS. Please, let us know if it works on iOS. It might be necessary to check for the OS before assigning a value to the "options.directory" property.
> 
> 1. The following change needs to be applied to the options object.
> 
> ```js
>     let options = {
>       html: '<h1>PDF TEST</h1>',
>       fileName: 'test',
>       directory: 'Download', // replace "Documents" with "Download" - I am not sure if this works on iOS 
>     };
> ```
> 
> 1. Moreover, you need to add a function to request permission. This is already mentioned on the readme file. However, it might not be obvious. An example code follows.
> 
> ```js
> import { Platform, PermissionsAndroid, } from "react-native";
> import RNHTMLtoPDF from 'react-native-html-to-pdf';
> 
> const fRequestAndroidPermission = async () => {
> 	// Refer to https://reactnative.dev/docs/permissionsandroid for further details on permsissions 
> 	try {
> 		const granted = await PermissionsAndroid.request(
> 			PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
> 			{
> 				title: "App1 Permission Request",
> 				message: "App1 needs access to your storage so you can save files to your device.",
> 				buttonNeutral: "Ask Me Later",
> 				buttonNegative: "Cancel",
> 				buttonPositive: "OK"
> 			}
> 		);
> 		
> 		if (granted === PermissionsAndroid.RESULTS.GRANTED) {
> 			console.log("permission is granted");
> 			return true; 
> 		} else {
> 			console.log("permission denied");
> 			return false; 
> 		}
> 	} catch (err) {
> 		console.error("fRequestAndroidPermission error:", err);
> 		return false; 
> 	}
> };
> 
> const createPDF = async () => {
> 	let options = {
> 	  html: '<h1>PDF TEST</h1>',
> 	  fileName: 'test',
> 	  directory: 'Documents', // replace 'Documents' with 'Dowloads' - I am not sure if it works on iOS! 
> 	};
> 
> 	if (Platform.OS === "android") {
> 		const permissionGranted = await fRequestAndroidPermission(); 
> 		if (!permissionGranted) {
> 			console.log("access was refused")
> 			return; 
> 		}
> 	}
> 
> 	let file = await RNHTMLtoPDF.convert(options);
> 	console.log(file.filePath);
> };
> createPDF(); 
> ```

You sir are a life saver!!

**Comment by forster007** [comment]
On iOS the app is crashing
